### PR TITLE
Bump up session pool size to prevent TimeoutErrors

### LINKED ISSUE #663: Fix sqlalchemy TimeoutError exceptions
I guess one of my recent features (#657, #658) broke the database connection in one of the API routes. I and other RIT students have discovered that the web container will now throw `sqlalchemy.exc.TimeoutError` exceptions almost immediately after the competition starts, right after the first requests to the website are made.

I haven't had the time to look at this yet, but I think I'll have a bit of time tomorrow afternoon to take a look.

Screenshot of the tail end of the stack trace from the docker logs:
bad

### PR DESCRIPTION
**Pull request by s-newman**
Fixes #663.

This probably isn't an ideal solution, but it works for now.

### CODE REVIEW

**Comment by s-newman** [comment]
Sweet, should be good to go now.
I need to set up notifications for travis builds on this repository...

**Comment by RustyBower** [comment]
So I'm actually gonna go through probably revert some of the changes that were made with incremental scoring (which should affect this), because it requires the engine to be running, and that behavior causes the example to not display any scores (they're all 0, because the engine hasn't run)

**Comment by s-newman** [comment]
I may have misunderstood you, but I modified Competition.save() to add initial scores of zero for each team. This way, all teams have a score even if the engine hasn't run yet.

**Comment by RustyBower** [comment]
I'm actually gonna back out the caching stuff, and approach it a different way. I really don't love the engine being forced to calculate scores, since it's out of the scope of what the engine is supposed to do.

**Comment by s-newman** [comment]
If you're planning on approaching this a different way, should we close this PR unmerged? Also, the incremental scoring feature could be reverted if that's not the preferred way to do things - the extra complexity isn't looking like it's worth it.

**Comment by pwnbus** [comment]
@s-newman Agreed, the revert PR is up at https://github.com/scoringengine/scoringengine/pull/667 so like you said, probably makes sense to close this PR.

**Pull request closed without merging**
