### PR TITLE
Incremental scoring

### LINKED ISSUE #621: Calcuate scores incrementally
Currently, teams scores are calculated by the Flask server every round from scratch and stored in the Redis cache. After enough checks have been completed, it can take a long time for the calculation to be completed. This calculation only needs to be performed once, but if several competitors try to repeatedly refresh the scoreboard before the results have been loaded into Redis, the Flask server will attempt to perform the calculation for each of the requests that were made. This can cause the front-end to fall over on slower hardware.

A more efficient way of calculating the scores would be to have the engine calculate the scores incrementally each round. The process would look like this:
- Wait for all of a round's checks to finish and get written to the database
- Load from the database each team's score from the previous round
- Add the point values of any passing services to the team's score
- Write the newly-calculated scores for the current round to the database

This will take away a lot of work from the Flask server, which could make the front-end snappier to use. However, it will require a new database table to be created, and each round would take a bit longer to complete. It would also require rewriting several of the API endpoints.

### PR DESCRIPTION
**Pull request by s-newman**
Closes #621.

### CODE REVIEW

**Comment by RustyBower** [comment]
Can you squash these :)

**Comment by RustyBower** [comment]
The only concern I have is the need to do a global recalculation, which happens when white team adds/removes points from scores in previous rounds, or sets checks to failed/passed. Those will require those rounds to be recalculated.

**Comment by RustyBower** [comment]
Also you bombed on Flake8:
./scoring_engine/models/team.py:69:22: F821 undefined name 'scores'
./scoring_engine/models/score.py:31:1: W293 blank line contains whitespace

**Comment by s-newman** [comment]
Yikes, currently working on fixing test failures...

**Comment by s-newman** [comment]
> The only concern I have is the need to do a global recalculation, which happens when white team adds/removes points from scores in previous rounds, or sets checks to failed/passed. Those will require those rounds to be recalculated.

I could add a "force recalculate" option in the White Team admin page that would perform this global recalculation on demand, if that would be useful. Then, the engine would run the recalculation at the beginning of the next round while waiting for checks to finish.

If this is an OK way of doing it, I'll go ahead and add it in to this PR.

**Comment by pwnbus** [comment]
@s-newman Instead of having a button that folks have to manually click, I wonder if it's something we could automagically do whenever whiteteam updates the status of a check (I don't know how long something like that will take on a larger data set).

**Comment by s-newman** [comment]
In fact, I think some sort of "force recalculate" option will _have_ to be added for in order for this to pass the following tests:
- `TestTeam.test_current_score`
- `TestTeam.test_place`
- `TestTeam.test_get_array_of_scores`
- `TestTeam.test_get_round_scores`

**Comment by RustyBower** [comment]
I have some thoughts on how to do per round/team updates on scores

**Comment by s-newman** [comment]
@RustyBower here's what I was thinking:
- Add an `update_points` method to the Service model that updates the points attribute for the service and then recalculate all scores for the service's team.
- Add an `update_result` method to the Check model that updates the result (pass/fail) for the check and then recalculate all scores for the check's team, starting at the round of the check.

Still trying to think of the best way to prevent TOCTOU issues between recalculation and the processing check results (see https://github.com/s-newman/scoringengine/blob/incremental-scoring/scoring_engine/engine/engine.py#L178-L186).

**Comment by RustyBower** [comment]
Sorry I meant to respond to this yesterday and forgot.

What I would like to see is the following:
- Ability to recalculate all scores (all rounds for all teams)
- Ability to recalculate all scores for a specific round (all teams in 1 round)
- Ability to recalculate all scores for a specific team (all round for 1 team)
- Ability to recalculate score for a team in a specific round.

All these tasks should be able to be dropped into celery to be picked up by the db worker to recalculate.

**Comment by s-newman** [comment]
Alright, well it looks like this finally works! Scores are automatically recalculated when an admin changes the points of a service or the result of a check. Here is how I have it implemented:

1. Admin makes a change to service points or check results
2. API endpoint queues a score recalculation for the team
3. While the engine waits for checks to finish, it will recalculate team scores for each queued team
4. Once all queued teams have been recalculated, the queue is cleared
5. Engine will wait for any remaining checks to finish and continues operation

I have the engine compute the score recalculations to prevent a recalculation from occurring while the engine is determining check results. Since the engine would normally be sitting idle during this time, it seemed like an acceptable time to perform the recalculations.

I benchmarked this implementation using the following method:
- turned on werkzeug request profiling
- built with `make rebuild-testbed-new`
- ran the engine for 30 rounds
- made a single request to `/api/overview/get_data`

Here is the profile results for a build of commit hash 52d96fdfaabfec6c83c1cc86238f7dd78762e1b9 (master, 6 commits behind master right now):
screenshot-2019-10-04_01-40-36

Here is the profile results for the current build of this branch:
screenshot-2019-10-04_03-10-53

Overall, an approximately 30% reduction in function calls and response time.

**Comment by s-newman** [comment]
Bump. LMK if there's anything lacking/should be added here.

**Comment by RustyBower** [comment]
Finally back home to take a peek at this. I'll throw some comments and stuff on this evening.

**Comment by RustyBower** [comment]
This LGTM, but I'll let @pwnbus do a pass on it as well since it's such a fundamental change.

Good stuff though @s-newman!

**Comment by pwnbus** [comment]
Sorry for the delay, finally got a chance to take a look, it looks great! Approving and merging now!

**Review by pwnbus — APPROVED** [review]

**Pull request merged**
