### PR TITLE
Implement OpenVPN check

### PR DESCRIPTION
**Pull request by joe-graham**
This pull request is to add an OpenVPN check (#579). This request does make a bit of a major change in that it requires the worker container to be running as privileged, since OpenVPN needs to be able to create a tun interface in order to execute. Similarly, OpenVPN also needs to execute as root within the worker. This required adding sudo and a sudoers file to the worker Dockerfile, but this change is somewhat small since the engine user is only allowed to run /usr/sbin/openvpn. The rest of the changes are pretty straightforward.

### CODE REVIEW

**Comment by RustyBower** [comment]
Running privileged would also fix some privilege issues with the NTP check. I don’t see any downside with this.

**Comment by pwnbus** [comment]
The build is failing during the integration test phase. Since you added another service to the testbed environment, you'll also need to update https://github.com/scoringengine/scoringengine/blob/master/tests/integration/test_integrations.py#L8 to be "15" and https://github.com/scoringengine/scoringengine/blob/master/tests/integration/test_integrations.py#L10 to be "1525".

**Comment by joe-graham** [comment]
Oh, woops! Sorry about that. Looks like the last commit fixed that.

**Comment by RustyBower** [comment]
Can you squash and rebase?

**Review by pwnbus — APPROVED** [review]

**Comment by pwnbus** [comment]
Great job, @joe-graham !

**Pull request merged**
