### PR TITLE
Modify worker to requeue jobs if worker is killed

### PR DESCRIPTION
**Pull request by pwnbus**
From http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-task_reject_on_worker_lost and http://docs.celeryproject.org/en/latest/userguide/configuration.html#task-acks-late

### CODE REVIEW

**Comment by RustyBower** [comment]
Looking through the docs it all looks sane.

**Comment by RustyBower** [comment]
Did you look at retry as well?

**Comment by pwnbus** [comment]
@RustyBower I was thinking about that, to making it retry a couple times. This was specifically for if we try and kill a worker mid round, BUT, if there's legitimate network error, that could be useful. Do you think retrying up to 3 times would be nice?

**Comment by RustyBower** [comment]
I think that makes sense

**Comment by pwnbus** [comment]
Apparently the retry is enabled by default, so we're good here.

**Pull request merged**
